### ISSUE TITLE
Won't open on mac - says damaged

### ISSUE THREAD

**Issue by Zacharybinx34** [Ecks1337/RyuSAK#58] opened 2023-03-12 01:31 UTC
M2 Macbook pro. - See title

**Comment by eager-ly** [comment] 2023-03-12 09:13
Same here. M1 max macbook pro. Upon trying to open after copying into applications:

""RyuSAK.app" is damaged and can't be opened. You should move it to the Trash."

**Comment by Ecks1337** [comment] 2023-03-15 03:43
duplicate of #34

**Closed by Ecks1337** 2023-03-15 03:43 UTC
