### ISSUE TITLE
Why did u remove Yuzu support? 

### ISSUE THREAD

**Issue by alerion921** [Ecks1337/RyuSAK#17] opened 2022-10-18 11:17 UTC
I would like to use this software but i prefer yuzu over ryujinx, can you please add back yuzu support?

**Comment by metalmight** [comment] 2022-10-20 21:19
I don't think it ever had Yuzu support. EmuSak did but this is RyuSak. My question is, why not include Yuzu?

**Comment by alerion921** [comment] 2022-10-21 05:48
Yuzu code was removed, this is essentialy a fork from the original code that had yuzu support.

**Comment by Ecks1337** [comment] 2022-10-21 21:52
Duplicate of #7, Closing

**Closed** 2022-10-21 21:52 UTC
